packages:
  - "packages/*"
  - "apps/*"

catalog:
  eslint: 9.34.0
  jest: 30.2.0
  jest-mock-extended: 4.0.0
  next: 15.5.4
  postcss: 8.5.6
  react: 19.2.0
  react-dom: 19.2.0
  tailwindcss: 4.1.14
  typescript: 5.9.3
  typescript-eslint: 8.46.2
  "@tailwindcss/postcss": 4.1.14
  "@types/jest": 30.0.0
  "@types/react": 19.2.0
  "@types/react-dom": 19.2.0
  "@types/node": 22.15.3
  "@types/mdx": 2.0.13